package tr;

// Generated May 24, 2012 11:06:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * MmConfigversion generated by hbm2java
 */
public class MmConfigversion implements java.io.Serializable {

	private MmConfigversionId id;
	private MmConfiguration mmConfiguration;
	private long savetime;
	private String versiontext;
	private Boolean checkedout;
	private Long originalversion;
	private String configuser;
	private String value;

	public MmConfigversion() {
	}

	public MmConfigversion(MmConfigversionId id,
			MmConfiguration mmConfiguration, long savetime, String configuser) {
		this.id = id;
		this.mmConfiguration = mmConfiguration;
		this.savetime = savetime;
		this.configuser = configuser;
	}

	public MmConfigversion(MmConfigversionId id,
			MmConfiguration mmConfiguration, long savetime, String versiontext,
			Boolean checkedout, Long originalversion, String configuser,
			String value) {
		this.id = id;
		this.mmConfiguration = mmConfiguration;
		this.savetime = savetime;
		this.versiontext = versiontext;
		this.checkedout = checkedout;
		this.originalversion = originalversion;
		this.configuser = configuser;
		this.value = value;
	}

	public MmConfigversionId getId() {
		return this.id;
	}

	public void setId(MmConfigversionId id) {
		this.id = id;
	}

	public MmConfiguration getMmConfiguration() {
		return this.mmConfiguration;
	}

	public void setMmConfiguration(MmConfiguration mmConfiguration) {
		this.mmConfiguration = mmConfiguration;
	}

	public long getSavetime() {
		return this.savetime;
	}

	public void setSavetime(long savetime) {
		this.savetime = savetime;
	}

	public String getVersiontext() {
		return this.versiontext;
	}

	public void setVersiontext(String versiontext) {
		this.versiontext = versiontext;
	}

	public Boolean getCheckedout() {
		return this.checkedout;
	}

	public void setCheckedout(Boolean checkedout) {
		this.checkedout = checkedout;
	}

	public Long getOriginalversion() {
		return this.originalversion;
	}

	public void setOriginalversion(Long originalversion) {
		this.originalversion = originalversion;
	}

	public String getConfiguser() {
		return this.configuser;
	}

	public void setConfiguser(String configuser) {
		this.configuser = configuser;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
