package tr;

// Generated May 24, 2012 11:06:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * MmConfigcoll generated by hbm2java
 */
public class MmConfigcoll implements java.io.Serializable {

	private int collectionid;
	private String name;
	private String description;
	private String ownergroup;
	private Boolean deleted;
	private Set mmConfigurations = new HashSet(0);
	private Set mmProvisionservers = new HashSet(0);

	public MmConfigcoll() {
	}

	public MmConfigcoll(int collectionid, String name, String ownergroup) {
		this.collectionid = collectionid;
		this.name = name;
		this.ownergroup = ownergroup;
	}

	public MmConfigcoll(int collectionid, String name, String description,
			String ownergroup, Boolean deleted, Set mmConfigurations,
			Set mmProvisionservers) {
		this.collectionid = collectionid;
		this.name = name;
		this.description = description;
		this.ownergroup = ownergroup;
		this.deleted = deleted;
		this.mmConfigurations = mmConfigurations;
		this.mmProvisionservers = mmProvisionservers;
	}

	public int getCollectionid() {
		return this.collectionid;
	}

	public void setCollectionid(int collectionid) {
		this.collectionid = collectionid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getOwnergroup() {
		return this.ownergroup;
	}

	public void setOwnergroup(String ownergroup) {
		this.ownergroup = ownergroup;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public Set getMmConfigurations() {
		return this.mmConfigurations;
	}

	public void setMmConfigurations(Set mmConfigurations) {
		this.mmConfigurations = mmConfigurations;
	}

	public Set getMmProvisionservers() {
		return this.mmProvisionservers;
	}

	public void setMmProvisionservers(Set mmProvisionservers) {
		this.mmProvisionservers = mmProvisionservers;
	}

}
