package tr;

// Generated May 24, 2012 11:06:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * MmIdrange generated by hbm2java
 */
public class MmIdrange implements java.io.Serializable {

	private String name;
	private Long startvalue;
	private Long rangelength;

	public MmIdrange() {
	}

	public MmIdrange(String name) {
		this.name = name;
	}

	public MmIdrange(String name, Long startvalue, Long rangelength) {
		this.name = name;
		this.startvalue = startvalue;
		this.rangelength = rangelength;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getStartvalue() {
		return this.startvalue;
	}

	public void setStartvalue(Long startvalue) {
		this.startvalue = startvalue;
	}

	public Long getRangelength() {
		return this.rangelength;
	}

	public void setRangelength(Long rangelength) {
		this.rangelength = rangelength;
	}

}
