package tr;

// Generated May 24, 2012 11:06:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * MmProvisionserverId generated by hbm2java
 */
public class MmProvisionserverId implements java.io.Serializable {

	private int collid;
	private int configid;
	private int configversionid;
	private int serverid;

	public MmProvisionserverId() {
	}

	public MmProvisionserverId(int collid, int configid, int configversionid,
			int serverid) {
		this.collid = collid;
		this.configid = configid;
		this.configversionid = configversionid;
		this.serverid = serverid;
	}

	public int getCollid() {
		return this.collid;
	}

	public void setCollid(int collid) {
		this.collid = collid;
	}

	public int getConfigid() {
		return this.configid;
	}

	public void setConfigid(int configid) {
		this.configid = configid;
	}

	public int getConfigversionid() {
		return this.configversionid;
	}

	public void setConfigversionid(int configversionid) {
		this.configversionid = configversionid;
	}

	public int getServerid() {
		return this.serverid;
	}

	public void setServerid(int serverid) {
		this.serverid = serverid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MmProvisionserverId))
			return false;
		MmProvisionserverId castOther = (MmProvisionserverId) other;

		return (this.getCollid() == castOther.getCollid())
				&& (this.getConfigid() == castOther.getConfigid())
				&& (this.getConfigversionid() == castOther.getConfigversionid())
				&& (this.getServerid() == castOther.getServerid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCollid();
		result = 37 * result + this.getConfigid();
		result = 37 * result + this.getConfigversionid();
		result = 37 * result + this.getServerid();
		return result;
	}

}
