package tr;

// Generated May 24, 2012 11:06:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * MmConfiguration generated by hbm2java
 */
public class MmConfiguration implements java.io.Serializable {

	private Long configid;
	private MmConfigcoll mmConfigcoll;
	private String name;
	private String configtype;
	private Boolean checkedout;
	private Boolean deleted;
	private Set mmConfigversions = new HashSet(0);

	public MmConfiguration() {
	}

	public MmConfiguration(MmConfigcoll mmConfigcoll, String name,
			String configtype) {
		this.mmConfigcoll = mmConfigcoll;
		this.name = name;
		this.configtype = configtype;
	}

	public MmConfiguration(MmConfigcoll mmConfigcoll, String name,
			String configtype, Boolean checkedout, Boolean deleted,
			Set mmConfigversions) {
		this.mmConfigcoll = mmConfigcoll;
		this.name = name;
		this.configtype = configtype;
		this.checkedout = checkedout;
		this.deleted = deleted;
		this.mmConfigversions = mmConfigversions;
	}

	public Long getConfigid() {
		return this.configid;
	}

	public void setConfigid(Long configid) {
		this.configid = configid;
	}

	public MmConfigcoll getMmConfigcoll() {
		return this.mmConfigcoll;
	}

	public void setMmConfigcoll(MmConfigcoll mmConfigcoll) {
		this.mmConfigcoll = mmConfigcoll;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getConfigtype() {
		return this.configtype;
	}

	public void setConfigtype(String configtype) {
		this.configtype = configtype;
	}

	public Boolean getCheckedout() {
		return this.checkedout;
	}

	public void setCheckedout(Boolean checkedout) {
		this.checkedout = checkedout;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public Set getMmConfigversions() {
		return this.mmConfigversions;
	}

	public void setMmConfigversions(Set mmConfigversions) {
		this.mmConfigversions = mmConfigversions;
	}

}
