package tr;

// Generated May 24, 2012 11:06:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * MmConfigversionId generated by hbm2java
 */
public class MmConfigversionId implements java.io.Serializable {

	private long configid;
	private long versionid;

	public MmConfigversionId() {
	}

	public MmConfigversionId(long configid, long versionid) {
		this.configid = configid;
		this.versionid = versionid;
	}

	public long getConfigid() {
		return this.configid;
	}

	public void setConfigid(long configid) {
		this.configid = configid;
	}

	public long getVersionid() {
		return this.versionid;
	}

	public void setVersionid(long versionid) {
		this.versionid = versionid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MmConfigversionId))
			return false;
		MmConfigversionId castOther = (MmConfigversionId) other;

		return (this.getConfigid() == castOther.getConfigid())
				&& (this.getVersionid() == castOther.getVersionid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getConfigid();
		result = 37 * result + (int) this.getVersionid();
		return result;
	}

}
