package tr;

// Generated May 24, 2012 11:06:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * MmServergroup generated by hbm2java
 */
public class MmServergroup implements java.io.Serializable {

	private long id;
	private String name;

	public MmServergroup() {
	}

	public MmServergroup(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
